
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 12 22:18:34 CET 2013
//----------------------------------------------------

package CalculiX;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 24;
  public static final int LT = 21;
  public static final int ELSE = 13;
  public static final int IDENT = 2;
  public static final int PLUS = 14;
  public static final int OR = 25;
  public static final int RPAREN = 6;
  public static final int THEN = 12;
  public static final int IN = 8;
  public static final int SUM = 20;
  public static final int SLASH = 17;
  public static final int STAR = 16;
  public static final int NOT = 26;
  public static final int TRUE = 9;
  public static final int IF = 11;
  public static final int LPAREN = 5;
  public static final int LE = 22;
  public static final int EOF = 0;
  public static final int FALSE = 10;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int LET = 7;
  public static final int EQ = 4;
  public static final int INTEGER = 3;
  public static final int EQEQ = 23;
  public static final int FOR = 18;
  public static final int TO = 19;
}

